# This is a basic workflow to help you get started with Actions
name: Checks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  detekt:
    name: Detekt - Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      - name: DeteKt
        uses: natiginfo/action-detekt-all@1.20.0-RC1
        with:
          args: --fail-fast --config config/detekt/detekt.yml
  tests:
    name: Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: ./gradlew app:testDebugUnitTestCoverage

      - name: Generate Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/jacoco/testDebugUnitTestCoverage

      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/jacoco/testDebugUnitTestCoverage

      - name: Upload Test Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: app/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml # optional
          flags: unittests
          name: pull-request
          fail_ci_if_error: true
          verbose: true